---
api_user: "root@pam"
api_password: "{{ pve_api_password }}"
api_host: "pve02"
snapname: "pre-updates"
vms:
  - 100
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 300
  - 400
