---
- name: Change Default Cockpit Port
  hosts: all
  become: true
  tasks:
    - name: Install cockpit
      when: ansible_facts['distribution'] == "RedHat"
      ansible.builtin.yum:
        name: cockpit
        state: present
    - name: Add SELinux Rule
      community.general.seport:
        ports: 9091
        proto: tcp
        setype: websm_port_t
        state: present
    - name: Add Cockpit (9091)
      ansible.posix.firewalld:
        port: 9091/tcp
        permanent: true
        immediate: true
        state: enabled
    - name: Remove Cockpit (9090)
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        immediate: true
        state: disabled
    - name: Make Directory (Web Console Port)
      ansible.builtin.file:
        path: "/etc/systemd/system/cockpit.socket.d"
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Update Config File (Web Console Port)
      ansible.builtin.blockinfile:
        path: "/etc/systemd/system/cockpit.socket.d/listen.conf"
        block: |
          [Socket]
          ListenStream=
          ListenStream=9091
        create: true
        owner: root
        group: root
        mode: "0644"
    - name: Restart and Enable Cockpit Service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        enabled: true
        name: cockpit.socket
