- name: Configure Desktop
  hosts: desktop.henrymillerfrazier.lan
  become: true
  become_user: noel
  gather_facts: false
  tasks:
    - name: Configure and enable libvirtd
      become_user: root
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

# Figure out an idempotent way to do this.
#    - name: Fix Libvirt Group Mapping
#      become_user: root
#      ansible.builtin.command: grep -E '^libvirt:' /usr/lib/group >> /etc/group

    - name: Configure and enable syncthing
      become_user: root
      ansible.builtin.service:
        name: syncthing@noel
        state: started
        enabled: true
