- name: Configure Desktop
  hosts: desktop.henrymillerfrazier.lan
  become: true
  become_user: noel
  gather_facts: false
  tasks:
    - name: Install packages
      become_user: root
      ansible.builtin.dnf:
        name:
          - kitty
          - git
          - flatpak
          - '@virtualization'
          - exa
          - nextcloud-client
          - htop
          - podman
          - unzip
          - cmatrix
          - flameshot
          - neofetch
          - telnet
          - NetworkManager-tui 
          - "https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm"
          - screen
          - syncthing
        state: present
        disable_gpg_check: true

    - name: Remove firefox
      become_user: root
      ansible.builtin.dnf:
        name: firefox
        state: absent

    - name: Configure and enable libvirtd
      become_user: root
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true

    - name: Configure and enable syncthing
      become_user: root
      ansible.builtin.service:
        name: syncthing@noel
        state: started
        enabled: true

    - name: Configure flathub remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - org.onlyoffice.desktopeditors
          - org.videolan.VLC
          - dev.goats.xivlauncher
          - com.valvesoftware.Steam
          - io.podman_desktop.PodmanDesktop
          - com.bitwarden.desktop
          - sh.ppy.osu
          - com.spotify.Client
          - tv.plex.PlexHTPC
          - org.signal.Signal
          - org.gimp.GIMP
          - io.github.hrkfdn.ncspot
          - net.lutris.Lutris
          - org.remmina.Remmina
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.brave.Browser
          - com.calibre_ebook.calibre
          - org.kde.okular
          - com.todoist.Todoist
          - com.usebottles.bottles
          - com.parsecgaming.parsec
          - org.yuzu_emu.yuzu
        state: present
        method: user

    - name: Create Downloads Directory
      ansible.builtin.file:
        path: ~/Downloads
        state: directory

    - name: Download Beeper # Manual install will have to be done to intergrate into desktop search
      ansible.builtin.get_url:
        url: "https://download.beeper.com/linux/appImage/x64"
        dest: ~/Downloads/

    - name: Create fonts directory
      ansible.builtin.file:
        path: ~/.local/share/fonts
        state: directory

    - name: Download FiraCode Fonts
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/FiraCode.tar.xz"
        dest: "~/.local/share/fonts/"
        remote_src: true

    - name: Download Material Design Fonts
      ansible.builtin.get_url:
        url: "https://github.com/Templarian/MaterialDesign-Font/blob/master/MaterialDesignIconsDesktop.ttf"
        dest: "~/.local/share/fonts/MaterialDesignIconsDesktop.ttf"
        mode: "0644"

    - name: Ensure needed directories are present
      loop: "{{ desktop_config_dir_list }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"

    - name: Ensure config files are copied
      loop: "{{ lookup('dict', desktop_config_files) }}"
      ansible.builtin.copy:
        src: "{{ item['value']['file'] }}"
        dest: "{{ item['value']['dest'] }}"
