---
- hosts: all
  become: true
  vars: 
    my_user: ansible
    my_group: ansible
  vars_files:
    - secrets.enc
  tasks:
  - name: Allow 'ansible' user to have passwordless sudo
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ my_group }}'
      line: '{{ my_group }} ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
  - name: Create new user
    ansible.builtin.user:
      name: "{{ my_user }}"
      groups: "{{ my_group }}"
