---
- hosts: all
  become: true
  vars: 
    my_user: noel
    my_group: wheel
  vars_files:
    - secrets.enc
  tasks:
  - name: Allow wheel group to have password sudo
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^{{ my_group }}'
      line: '{{ my_group }} ALL=(ALL) ALL'
      validate: 'visudo -cf %s'
  - name: Create new user
    ansible.builtin.user:
      name: "{{ my_user }}"
      groups: "{{ my_group }}"
      password: "{{ noel_password | password_hash('sha512')}}"
