---
- hosts: hypervisors
  tasks:
  - name: Delete VM snapshot
    community.general.proxmox_snap:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      vmid: "{{ item }}"
      state: absent
      snapname: "{{ snapname }}"
    loop: "{{ vms }}"
