- name: Deploy Rootful Containers
  hosts: containers.henrymillerfrazier.lan
  become: true
  gather_facts: false
  tasks:
    - name: Create user
      loop: "{{ my_containers }}"
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        state: "present"
    - name: Create directory for container files
      loop: "{{ my_containers }}"
      ansible.builtin.file:
        path: "{{ containers_directory }}/{{ item['name'] }}" # e.g: /opt/containers/{{ container_name }}
        state: directory
        owner: "{{ item['name'] }}"
        group: "{{ item['name'] }}"
        mode: '0750'
    - name: Set file ownership with podman unshare
      loop: "{{ my_containers }}"
      become_user: "{{ item['name'] }}"
      ansible.builtin.command: "podman unshare chown {{ item['name'] }}:{{ item['name'] }} -R {{ containers_directory }}/{{ item['name'] }}"
    - name: Create container
      loop: "{{ my_containers }}"
      containers.podman.podman_container: "{{ item['container_config'] }}"
    - name: Start and enable container-dashmachine.service
      loop: "{{ my_containers }}"
      ansible.builtin.systemd:
        name: "container-{{ item['name'] }}.service"
        state: started
        enabled: true
        daemon_reload: true
    - name: Create firewall rules on host
      loop: "{{ host_firewall_ports }}"
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
