---
- name: Deploy Authorized Keys
  hosts: all,!desktops
  become: true
  gather_facts: false
  vars_files:
    - secrets.enc
  tasks:
    - name: Make directories
      loop: "{{ standard_users }}"
      ansible.builtin.file:
        path: "/home/{{ item['name'] }}/.ssh"
        state: directory
        owner: "{{ item['name'] }}"
        group: "{{ item['name'] }}"
        mode: "0700"
    - name: Deploy ansible controller public key
      notify: Restart sshd
      loop: "{{ standard_users }}"
      ansible.builtin.blockinfile:
        path: "/home/{{ item['name'] }}/.ssh/authorized_keys"
        block: "{{ item['pubkeys'] }}"
        state: present
        owner: "{{ item['name'] }}"
        group: "{{ item['name'] }}"
        mode: "0600"
        create: true
  handlers:
    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
        daemon_reload: true
