---
- name: Disable ssh password login
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Change password authentication to no
      notify: Restart SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        backrefs: true
  handlers:
    - name: Restart SSH
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: sshd
