---
- hosts: vms
  tasks:
  - name: Change password authentication to no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      backrefs: yes
  - name: Restart SSH
    systemd: 
      state: restarted
      daemon_reload: yes
      name: sshd
