---
- hosts: all
  become: true
  tasks:
  - name: Change password authentication to no
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      backrefs: yes
  - name: Restart SSH
    ansible.builtin.systemd: 
      state: restarted
      daemon_reload: yes
      name: sshd
