---
- name: Install podman
  hosts: container_hosts
  become: true
  tasks:
    - name: Set container_manage_cgroup on
      ansible.posix.seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true
    - name: Install podman
      ansible.builtin.yum:
        name:
          - podman
          - podman-docker
        state: present
    - name: Reboot server
      ansible.builtin.reboot:
