---
- name: Install Prometheus Monitoring
  hosts: all, !monitor, !desktops
  become: true
  tasks:
    - name: Add repository
      ansible.builtin.yum_repository:
        name: prometheus
        description: Prometheus Yum Repo
        baseurl: "https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch"
        gpgcheck: true
        gpgkey:
          - "https://packagecloud.io/prometheus-rpm/release/gpgkey"
          - "https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm"
        metadata_expire: 300
    - name: Install Prometheus and Node Exporter
      ansible.builtin.yum:
        name: 'prometheus2, node_exporter'
        state: present
    - name: Copy Config
      ansible.builtin.template:
        src: prometheus_client.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: "0644"
    - name: Enable Service (Prometheus and Node Exporter)
      loop:
        - prometheus.service
        - node_exporter.service
      ansible.builtin.service:
        state: started
        daemon_reload: true
        enabled: true
        name: "{{ item }}"
    - name: Update Firewall
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        immediate: true
        state: enabled
