---
- hosts: all, !monitor
  become: true
  tasks:
  - name: Add repository
    yum_repository:
      name: prometheus
      description: Prometheus Yum Repo
      baseurl: "https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch"
      gpgcheck: yes
      gpgkey: 
        - "https://packagecloud.io/prometheus-rpm/release/gpgkey"
        - "https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm"
      metadata_expire: 300
  - name: Install Prometheus and Node Exporter
    yum:
      name: 'prometheus2, node_exporter'
      state: latest
  - name: Copy Config
    template:
      src: prometheus_client.yml.j2
      dest: /etc/prometheus/prometheus.yml
  - name: Enable Service (Prometheus)
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: prometheus.service
  - name: Enable Service (Node Exporter)
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: node_exporter.service
  - name: Update Firewall
    firewalld:
      port: 9100/tcp
      permanent: yes
      immediate: yes
      state: enabled
