---
- name: Install Node Exporter
  hosts: all, !desktops
  become: true
  tasks:
    - name: Add repository
      ansible.builtin.yum_repository:
        name: prometheus
        description: Prometheus Yum Repo
        baseurl: "https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch"
        gpgcheck: false
        gpgkey:
          - "https://packagecloud.io/prometheus-rpm/release/gpgkey"
          - "https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm"
        metadata_expire: 300
    - name: Install Node Exporter
      ansible.builtin.yum:
        name: node_exporter
        state: present
    - name: Remove Prometheus
      ansible.builtin.yum:
        name: prometheus2
        state: absent
    - name: Enable Service
      ansible.builtin.service:
        state: started
        daemon_reload: true
        enabled: true
        name: "node_exporter.service"
    - name: Update Firewall
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        immediate: true
        state: enabled
