---
- name: register rhel server
  hosts: new_server
  become: true
  vars: 
    rhc_auth:
      activation_keys:
        keys:
          - "rhel_8_server"
    rhc_organization: "11785246"
  roles:
    - linux-system-roles.rhc
# TODO: Figure out a way to add SSH key to newly create RHEL VM
- import_playbook: create_noel_user.yml
- import_playbook: create_veeam_user.yml
- import_playbook: deploy_authorized_keys.yml
- import_playbook: disable_ssh_password_login.yml
- import_playbook: disable_remote_root_login.yml
- import_playbook: change_default_cockpit_port.yml
- import_playbook: install_prometheus_monitoring.yml
- import_playbook: setup_prometheus_monitoring_server.yml
- import_playbook: install_mosh.yml
- import_playbook: update_server.yml
