my_bashrc: |

  # ===============================
  # General environment variables
  # ===============================

  # Set editor for oc commands
  export EDITOR=/usr/bin/vim

  # Set bash history size
  export HISTSIZE=10000

  # Set bash history timestamps
  export HISTTIMEFORMAT="%F %T "

  # Set pager not to clear on exit
  export LESS='-X'

  export TERM=xterm-256color

  # Append to .bash_history
  PROMPT_COMMAND="$PROMPT_COMMAND; history -a; history -n"

  # ===============================
  # Git bash environment variables
  # ===============================

  source /usr/share/git-core/contrib/completion/git-prompt.sh
  
  # ===============================
  # Configure PS1
  # ===============================
  source ~/.bash-powerline/bash-powerline.sh

  # ===============================
  # Ansible aliases (ansible-core)
  # ===============================

  alias ap="ansible-playbook"
  alias apsc="ansible-playbook --syntax-check"
  alias apc="ansible-playbook --check"
  alias acd="ansible-config dump"
  alias av="ansible --version"
  alias aig="ansible-inventory --graph"

  # ================
  # General aliases
  # ================

  # stop using scp
  alias scp="echo -e \nStop using scp\n\nSee https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know"
  alias ls="exa"
  alias betterdiscord-update="DISC_CONFIG=\"\$HOME/.var/app/com.discordapp.Discord/config/discord\" && BD_ASAR=betterdiscord.asar && wget --timestamping -P \"\${DISC_CONFIG}/../BetterDiscord/data\" -- \"https://github.com/BetterDiscord/BetterDiscord/releases/latest/download/\${BD_ASAR}\" && DISC_VER=\"\$(ls --sort=time --time=creation \"\${DISC_CONFIG}\" | grep -E -m 1 '^[0-9]+\\.[0-9]+\\.[0-9]+\$')\" && echo -e \"require('../../../../BetterDiscord/data/\${BD_ASAR}');\\nmodule.exports = require('./core.asar');\" | tee \"\${DISC_CONFIG}/\${DISC_VER}/modules/discord_desktop_core/index.js\" && echo -e \"\\nBetterDiscord installed. Restart Discord if currently running.\" || echo -e \"\\nInstallation failed.\""


