---
# Public Keys (In the Order Below)
# Work Laptop
# Desktop
# iPad
pubkeys: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB5OeiBUihcLAmfrRsaJMT/vfJVJ2uEf2mtxlWK8KTvfapNJhP973NSL7xInvu7L8/K5HimTZZs0mrZvcPQVD/Jo5p7091LvmZl29S63TO/RGT+xgH2+BurZsDE5BumZUB3iO7De7e2wMc9VEQjXcIIJ66JEjNSDuw4F7wSIifm8nhIU2WSJOYSQzs0A5SGwJ6xo9aIWvB0IChLNZSTiRAYp9VAnucGB5NPxpiPuDUsA/gW8lyo6rq6CWTisaId2E7gcVsSIXIISg4LPXIV792jo7ckUj6OqMUZz+NkvcYa7yuRXyIlSTrBTWGgBrZSrYT1cofY3BOVHuhtx06GetqRjtsUCCW/ju4VuuOAt91CHt8jsHXCdjF72UyrSB9dYX9C2yUVwQ0Tw5rSc5C6yF26Yxi3sZW95u5Hb0WDztjxuSSg+2tK08CynYgfDYasIz/yoWoxRQEr4ErvxeZWM3Me1rGSjW7p5ptu/pug4qjp4N15qY86TqiSHdR7LGio0k= noel@desktop.henrymillerfrazier.lan
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvlFzHY8Mwo88n7UirX/J+xHQt2GTnI7krFFC9WbJBhPjJCg8QtQHWco9V+x7uZ0xl0UXSexgLjEu4X6pldnH9fH5aW8K9eGVxF2a3qxzjGMp3pmqQscMpwA1VlcWiUIgYSwX+UEj79eB+vXJettojRWPgNTkdceIrnaGWZRnGOGQLL99Fmiij1t8gn0Z6Fx/pC27wi2Grzy4Xit0c4+ep5iyzNQQ45TSEEL7JH8em+lUctsG/FjS6UsXesTK194HDaXRvIAHGUaBEyecpkzhNhv7qzcS7DMYPakdjA8m14+2yl69LoOYEDBBKvhP9zn1sc0tyJ3P4jgjEsYtCBifT noel@ipad

standard_users:
  - name: noel
    groups: 
      - wheel
    password: "{{ noel_password }}"
    sudo: true
    passwordless_sudo: false
    pubkeys: "{{ pubkeys }}"
  - name: ansible
    sudo: false
    passwordless_sudo: true
    # This is a specific key install on the ansible server
    pubkeys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDP7cw7s685Rlj9Hw3/qqdS4ek6PtTBavjMyZQacbUUq/jTTaQFG/T3WecxzdYA9gBltEJZlKafqyWfcQotdbEZftqK2Y9jo8NKEz/lIQYzD828YPBNcVG68IPDHMJSerX/zZR0JB+S1U1lEY/GXdjoArXPl9t/9/o5mx+QX+W0W/gXAbcoCsqYVfJivruQayQGcI6K7k/ytitCcAdndhMn1QANSVLNKYCsYxrX+JW6nsFRWC2PBws9btJzADY5XfaLeAcN6iNNK6HCY1Bs5OJebpKOdz0+wcY4SVp1K6tqxcp/phBCwhv+uneMYwHZmUFmthLz6eNwbvil/JrRGU+WuwCUUCNxG0c2W3+t2PFI/gxprfKED9DLzHd95t3SQ2v4FZVOIEczdszWuEhvM5oAW/wGH3YH741PvcC3sGp6d0I+05lzm6BaNpwb8ERCYwEoXiDCshrmumxXFfXG3K/fuoEqGYFfJLvSKaejQUhEAuebhZ0vlRJ45sTO4mHS6Y8= noel@desktop.henrymillerfrazier.lan

rhc_auth:
  activation_keys:
    keys: "{{ rhc_keys }}"
  rhc_organization: "{{ rhc_organization }}"
