---
# Public Keys (In the Order Below)
# Work Laptop
# Desktop
# iPad
pubkeys: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNYWTjyv6tGKpyGOx0E6jBd+8VsF1YpMgPQLVE4fu3FbfJlD/MclqIlvNs4EK14nbC/b7w6JIx3VFfgYv1wgv+TnqH+HWJmMHjqn124Qf5n+APckM1uvgFiLoRCv2uoqDodmn0aqF/4aj+sZAxAFvAYHRdxzOOkjkyjEfyvdWEwSWYsaqtj52M9upCifmDXRjKXm0x+V65oR3mUudHTi8fSHQIgF5OhyGhDK8uUB9aiG5aVnw2Vr3Y+LwuMNa5jJeodmM4Jx+6Im5x5tVkq0fHXkoyyZXojw2eRDIeBz3SjCLDjItvOm194jtsVIsO4I5hnNKAYwKFj19+Q2ct0Oe+z+P3OYxwjVUIoGSMobQaMwIY1K02EP0X+qAK9YaqejZbp9Im39O+9EKci6ECq7m8kifrU/CLkbDCuT7lC558/NlgOfkVsxVFyo9iYelDYRWwkNJUknImxO8arqwgnNLv4v06ehqfHFYMZ+FWDcYWPW3+NbH9jZW9DePCGkYbXfc= V-MillerNR@R065568
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB5OeiBUihcLAmfrRsaJMT/vfJVJ2uEf2mtxlWK8KTvfapNJhP973NSL7xInvu7L8/K5HimTZZs0mrZvcPQVD/Jo5p7091LvmZl29S63TO/RGT+xgH2+BurZsDE5BumZUB3iO7De7e2wMc9VEQjXcIIJ66JEjNSDuw4F7wSIifm8nhIU2WSJOYSQzs0A5SGwJ6xo9aIWvB0IChLNZSTiRAYp9VAnucGB5NPxpiPuDUsA/gW8lyo6rq6CWTisaId2E7gcVsSIXIISg4LPXIV792jo7ckUj6OqMUZz+NkvcYa7yuRXyIlSTrBTWGgBrZSrYT1cofY3BOVHuhtx06GetqRjtsUCCW/ju4VuuOAt91CHt8jsHXCdjF72UyrSB9dYX9C2yUVwQ0Tw5rSc5C6yF26Yxi3sZW95u5Hb0WDztjxuSSg+2tK08CynYgfDYasIz/yoWoxRQEr4ErvxeZWM3Me1rGSjW7p5ptu/pug4qjp4N15qY86TqiSHdR7LGio0k= noel@desktop.henrymillerfrazier.lan
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvlFzHY8Mwo88n7UirX/J+xHQt2GTnI7krFFC9WbJBhPjJCg8QtQHWco9V+x7uZ0xl0UXSexgLjEu4X6pldnH9fH5aW8K9eGVxF2a3qxzjGMp3pmqQscMpwA1VlcWiUIgYSwX+UEj79eB+vXJettojRWPgNTkdceIrnaGWZRnGOGQLL99Fmiij1t8gn0Z6Fx/pC27wi2Grzy4Xit0c4+ep5iyzNQQ45TSEEL7JH8em+lUctsG/FjS6UsXesTK194HDaXRvIAHGUaBEyecpkzhNhv7qzcS7DMYPakdjA8m14+2yl69LoOYEDBBKvhP9zn1sc0tyJ3P4jgjEsYtCBifT noel@ipad

standard_users:
  - name: noel
    groups: 
      - wheel
    password: "{{ noel_password }}"
    sudo: true
    passwordless_sudo: false
    pubkeys: "{{ pubkeys }}"
  - name: ansible
    groups:
      - ansible
    sudo: false
    passwordless_sudo: true
    pubkeys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgPboMGs00UkrBaV8qCv4wGxEoBsypObaB6/amu4HyUh0FJFY3HlEzlHLrkQALM6JzsQfBug9B2OckYFbrNGhymsoanGU4JbN//i58e5qCskrf86wYTY1JmLV0tlqZ5vg0EICFZGbhTDI4fL1nNptGPjCAVAcw+YJkBGU0O/ib4hsFScPGiMVwVCbmAPxJ2B6a+VM5mX5WwZt8pQWJonj8OTOSCBDEY9DtkIJ3PkxSyJrq2gbe2evFbuuowRMppZdWPzow31a26nCpBhz0CSFJLTqJM7yYMIRtpyL8X+nrSkqu1PcXkTJK5vhx5L1b2UEr9ySu63jTAUiTRkSGIV5/wIbEyz/rALYE84jNonnjvmXA4zkzpWFFBn8W8SHOZC2Udkh8g/L4nboY+MykIrr2mPCO5rxjQy57oRMox2nfNLLO+OzOf4e0NEV4y7iQDAmOOGvnyJ9PRsDd7QpVKxt5RZuPXycEI4NJVbdBA9oJBG/jgjPaONnQugcH4OTKEis= root@ansible.henrymillerfrazier.lan
  - name: veeam
    groups:
      - veeam
    sudo: false
    passwordless_sudo: true
    pubkeys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjEETsPc3bc7JIr76/ufIA37tNAFEzJHeNXO7TRBLCvFTOwkivJVw3+YZyfgz4VMRXM9KTQLo0CNAA5nr38L7bGZTijk5S3q0C+XIpuy3Ky+LvujkM4h4EEcrQXMR2jeGMo8dFelpL71x/Csq6jSB/Jfbh9AfhK9XcmuMQS2Z45/rkFEsjRSnePoRdZPnwgPRQ4pKDZ1WqUx78dkDpGlWv9MNGOFQZsWV81hFcXzebEir1R9E4JOYIss56dVivFpvFpmLyc/KlwSqXAa1EIQy9hgxpNlkZY3ICbElT2SCpTUtzvP6Ufc/rwZReXj+0whKz560aLhG1ezY3nLf4BKWmy2LQRptnoB8GKTwJRuo2Rqmk59Dn5WZI41rkz0mtPhPiDfomBmzBIqavl46qirBXvxE+VXHtrItfDXfOF9ma3MrmP+YJAeTlVJ+vhFo48pD1Z7iALR7OvDMFVL7Yz27J6AgprgEaatB4nSrycF01pGkxG0O43iyACMoY9JuFTR0= noelm@desktop

rhc_auth:
  activation_keys:
    keys: "{{ rhc_keys }}"
  rhc_organization: "{{ rhc_organization }}"
