containers_directory: /opt/containers
host_firewall_ports:
  - "5000/tcp"
  - "3478/udp"
  - "10001/udp"
  - "8080/tcp"
  - "8443/tcp"
  - "1900/udp"
  - "8843/tcp"
  - "8880/tcp"
  - "6789/tcp"
  - "5514/udp"
  - "8081/tcp"
  - "8989/tcp"
  - "7878/tcp"
my_containers:
  - name: dashmachine
    container_config:
      name: "dashmachine"
      image: "docker.io/rmountjoy/dashmachine:latest"
      subuidname: "dashmachine"
      subgidname: "dashmachine"
      ports:
        - "5000:5000"
      volumes:
        - "{{ containers_directory }}/dashmachine:/dashmachine/dashmachine/user_data:Z"
      generate_systemd:
        new: true
        path: "/etc/systemd/system/"
  - name: unifi
    container_config:
      name: "unifi"
      image: "ghcr.io/linuxserver/unifi-controller"
      subuidname: "unifi"
      subgidname: "unifi"
      ports:
        - "3478:3478/udp"
        - "10001:10001/udp"
        - "8080:8080"
        - "8443:8443"
        - "1900:1900/udp" #optional
        - "8843:8843" #optional
        - "8880:8880" #optional
        - "6789:6789" #optional
        - "5514:5514/udp" #optional
      volumes:
        - "{{ containers_directory }}/unifi:/config:Z"
      generate_systemd:
        new: true
        path: "/etc/systemd/system/"
  - name: sabnzbd
    container_config:
      name: sabnzbd
      image: "lscr.io/linuxserver/sabnzbd:latest"
      subuidname: "torrent"
      subgidname: "torrent"
      env:
        PUID: 1009
        PGID: 1010
      ports:
        - "8081:8080"
      volumes:
        - "{{ containers_directory }}/sabnzbd:/config:Z"
        - "/data/files/Downloads:/downloads"
        - "/incomplete-downloads:/incomplete-downloads"
      generate_systemd:
        new: true
        path: "/etc/systemd/system/"
  - name: sonarr
    container_config:
      name: sonarr
      image: "lscr.io/linuxserver/sonarr:latest"
      subuidname: "torrent"
      subgidname: "torrent"
      env:
        PUID: 1009
        PGID: 1010
      ports:
        - "8989:8989"
      volumes:
        - "{{ containers_directory }}/sonarr/config:/config:Z"
        - "/data/files/TV:/tv"
        - "/data/files/Downloads:/downloads"
      generate_systemd:
        new: true
        path: "/etc/systemd/system/"
  - name: radarr
    container_config:
      name: radarr
      image: "lscr.io/linuxserver/radarr:latest"
      subuidname: "torrent"
      subgidname: "torrent"
      env:
        PUID: 1009
        PGID: 1010
      ports:
        - "7878:7878"
      volumes:
        - "{{ containers_directory }}/radarr/config:/config:Z"
        - "/data/files/Movies:/movies"
        - "/data/files/Downloads:/downloads" 
      generate_systemd:
        new: true
        path: "/etc/systemd/system/"
